language: node_js
node_js:
  - stable
  - '--lts'
before_script:
  - npm run setup
  - npm run build
deploy:
  provider: script
  edge: true
  email: jaissatai6@gmail.com
  skip_cleanup: true
  script: npx semantic-release
  on:
    branch: master
    node_js: '--lts'
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
env:
  global:
    - secure: wgm0NIaHLhcNRGpyR1Hi1942NOG4wy3WQxzFyGZzBMOqu4e8N4fyl11pCB56HBtIOSuFBQ99xO9Ee5gDMY4EXxVPF76VzR3CAQNR1v5HHmFZre+wt8yViwNoWvl816g/qZPCRd1NUSIRUeT5xdG4NfWXW52h0FEML4mBLgwbL13nuRinMWyVZZOssfo/mC7v9fg1hGYohH+7pwDBD1piOE5L9p7gG74TLqUAK4QsZwYkDNUWtadXMG9953wQWPgX9cU+kBBwtW/fW4R6oh+nBxS+o1cSj2JOYoNknJKeUVsIUwd26p4PwPB/hY6R+dTmBYZC/dbT6q1x2j1x7cqlDoBECDXltfmmLberXc2jqR0EmJiERzu9hZvovkg9lueTmn0ki02lxTppLwYObp8cyAdooVCYfnetF1fZgck3mKdRuMmzCy54OsTJsLcJmx4c8pfit9wxpUWO1t25suqI2vfmLbn2z2GRUW/8jxWRyjhihoOjFmS39SGjE7vzNtKRbEsvvAeYteLzKKyatznlqx7TOEnZhmydIRWjp2MTBf7CQ8X6s6IqS5ZvxKm7MvPKaW9TFB6rtlDWRdCXoKYEZtBXmTiS9PosslzqmIQ/BrpZeECNb1LG0smR5yLfXqOL8OEQh8zj7Y3NiC2OZMxj/U73mY6Jnhj9Fu5G6f1yIsk=
    - secure: hxOYqK94WsyxMpROfl31Vqq/PA5XnDaZ2aI8/fh8c2mj+dVjduEaVCGcr+k/jCEgu86znRbdK65i1TaGbZQL4d65tZ6waiimlPNlAod4OoysVba4c8zVOC5L0Dn3zVzeSe2uuYuULX9eV0hej7Q99ChgOqIybmrntxq3ofKPoWQesun5I/Hpa9LXGlPd0FbtH1mBnN9VA6gq65uUc+w0Rvn4gQwx3lJ/m0miv7y8fP5AvqCiDhfKlD8/xiT4+yONMf0f5zgLCb//+nNm9tnAABtur/pjU0q3nH+UNadmp8w64XANVQNdksFKdKTw/i1hhcZXDY51TqPCG1UaI/Oxh8oGT1P+guEpIL/ZAuKZMp4UTwg0GaMTM/0GiWs0dzEk7HZLuVitfCD2Z4QUJ7VY1yfTRz3ryO4Frrz4IhjadUvt3r/V+//MFKObZDbNP+TW9n+Qim6Ak1UIz+xBeY1n7MkuN2EFGJ+7KQ+jKuaRzdV1H7vIwhZ2j3nNrFXfPCYUhx07pvqE8MJnIneYhgOAh7SvmiAaThGWLSLqlDhOonhjEBFlLiA0XYvNe6kGbmfnyEd4UU7ezpnI+Q+HlAIULkhQnDOSsVuMzHqSviR97GEHoNxQ3BiHREAe3PMg0a9t++SLDCyZ7rNgnfSlGoVdAoscthMG/q/5zU7qEXRABig=
